-- TESTS
call enter_combat(1,1);
call enter_combat(2,1);
call enter_combat(3,1);
call reset_round(1); -- round 0
call cast_spell(1,1,2);
call cast_spell(1,1,3);
call cast_spell(1,2,2);
call cast_spell(2,3,1);
call cast_spell(2,4,3);
call cast_spell(2,4,3);
call cast_spell(3,5,1);
call cast_spell(3,6,1);
call cast_spell(3,4,1);
call cast_spell(3,6,2);
call reset_round(1);
call queue_loot_item(3,1);
call queue_loot_item(3,1);
call cast_spell(3,4,1);
call cast_spell(3,6,2);
call cast_spell(1,1,2);
call cast_spell(1,1,3);
call cast_spell(1,2,2);
call cast_spell(2,3,1);
call cast_spell(2,4,3);
call cast_spell(2,4,3);
call reset_round(3);
select*from battle_log;
select*from turn_log;
select*from characters;
select*from character_inventory where owner_id = 2;
select*from battle_inventory;
select*from character_locations order by character_id, change_time desc;